import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ScrollToTopButton from "./components/ScrollToTopButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-[90%] mx-auto bg-gray-100`} 
      >
        <div className="flex flex-col w-[98%] mx-auto shadow-black shadow-lg">
            
          <main className="flex-grow  md:mb-[37%] z-[50] bg-gray-100">
          <Header />
            {children}</main>
         < ScrollToTopButton />
          <Footer />
          </div>
      </body>
    </html>
  );
}
